name: socket_io_common
description: Socket.io common parser library.
version: 0.9.0
author: jumperchen <jumperchen@potix.com>
homepage: https://www.zkoss.org

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  uuid: "1.0.3"
  logging: any

dev_dependencies:
  test: ^1.0.0
