name: socket_io_common
description: Socket.io common parser library.
version: 2.0.0-beta.0
homepage: https://www.zkoss.org
repository: https://github.com/rikulo/socket_io_common
issue_tracker: https://github.com/rikulo/socket_io_common/issues

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  logging: ^0.11.4